# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/xilinx_2017/Projects/gsense2020_v121/gsense2020_v121.srcs/sources_1/bd/BRAM_SPI/ip/BRAM_SPI_auto_pc_1/BRAM_SPI_auto_pc_1.xci
# IP: The module: 'BRAM_SPI_auto_pc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/xilinx_2017/Projects/gsense2020_v121/gsense2020_v121.srcs/sources_1/bd/BRAM_SPI/ip/BRAM_SPI_auto_pc_1/BRAM_SPI_auto_pc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_SPI_auto_pc_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/xilinx_2017/Projects/gsense2020_v121/gsense2020_v121.srcs/sources_1/bd/BRAM_SPI/ip/BRAM_SPI_auto_pc_1/BRAM_SPI_auto_pc_1.xci
# IP: The module: 'BRAM_SPI_auto_pc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/xilinx_2017/Projects/gsense2020_v121/gsense2020_v121.srcs/sources_1/bd/BRAM_SPI/ip/BRAM_SPI_auto_pc_1/BRAM_SPI_auto_pc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_SPI_auto_pc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
