set_property SRC_FILE_INFO {cfile:D:/xilinx_2017/Projects/gsense2020_v121/gsense2020_v121.srcs/constrs_1/new/spi_pin.xdc rfile:../../../gsense2020_v121.srcs/constrs_1/new/spi_pin.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF20 [get_ports spi_data]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF19 [get_ports spi_out]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF22 [get_ports spi_read]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE22 [get_ports spi_write]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE18 [get_ports spi_clk]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD20 [get_ports sys_rst_n]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB24 [get_ports fpga_en]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB17 [get_ports {cmos_dop[0]}]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD16 [get_ports {cmos_dop[1]}]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W13 [get_ports {cmos_dop[2]}]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE13 [get_ports {cmos_dop[3]}]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC21 [get_ports {decoder[0]}]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC22 [get_ports {decoder[1]}]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA19 [get_ports {decoder[2]}]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB19 [get_ports {decoder[3]}]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE20 [get_ports {decoder[4]}]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE21 [get_ports {decoder[5]}]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W20 [get_ports {decoder[6]}]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y20 [get_ports {decoder[7]}]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA20 [get_ports {decoder[8]}]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB20 [get_ports {decoder[9]}]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W18 [get_ports {decoder[10]}]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W19 [get_ports {decoder[11]}]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF25 [get_ports {ctr_sig_w[0]}]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC24 [get_ports {ctr_sig_w[1]}]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC23 [get_ports {ctr_sig_w[2]}]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB25 [get_ports {ctr_sig_w[3]}]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA22 [get_ports {ctr_sig_w[4]}]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC18 [get_ports {ctr_sig_w[5]}]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF24 [get_ports {ctr_sig_w[6]}]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB26 [get_ports {ctr_sig_w[7]}]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC26 [get_ports {ctr_sig_w[8]}]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA23 [get_ports {ctr_sig_w[9]}]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD23 [get_ports {ctr_sig_w[10]}]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA25 [get_ports {ctr_sig_w[11]}]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD24 [get_ports {ctr_sig_w[12]}]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE25 [get_ports {ctr_sig_w[13]}]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE26 [get_ports {ctr_sig_w[14]}]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD25 [get_ports {ctr_sig_w[15]}]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD26 [get_ports {ctr_sig_w[16]}]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC19 [get_ports {ctr_sig_w[17]}]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC14 [get_ports clk_in_p]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC13 [get_ports clk_out_p]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets BRAM_SPI_i/receiver_0/inst/ser2par/inst/data_in_from_pins_int_0]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets BRAM_SPI_i/receiver_0/inst/ser2par/inst/data_in_from_pins_int_1]
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets BRAM_SPI_i/receiver_0/inst/ser2par/inst/data_in_from_pins_int_2]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets BRAM_SPI_i/receiver_0/inst/ser2par/inst/data_in_from_pins_int_3]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[0]}]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[10]}]
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[11]}]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[12]}]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[13]}]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[14]}]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[15]}]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[16]}]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[17]}]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[18]}]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[19]}]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[1]}]
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[20]}]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[21]}]
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[22]}]
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[23]}]
set_property src_info {type:XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[24]}]
set_property src_info {type:XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[25]}]
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[26]}]
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[27]}]
set_property src_info {type:XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[28]}]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[29]}]
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[2]}]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[30]}]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[31]}]
set_property src_info {type:XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[3]}]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[4]}]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[5]}]
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[6]}]
set_property src_info {type:XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[7]}]
set_property src_info {type:XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[8]}]
set_property src_info {type:XDC file:1 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[9]}]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 2 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list BRAM_SPI_i/clk_wiz_0/inst/clk_out2]]
set_property src_info {type:XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {BRAM_SPI_i/receiver_0/inst/recv/ch2/pos[0]} {BRAM_SPI_i/receiver_0/inst/recv/ch2/pos[1]} {BRAM_SPI_i/receiver_0/inst/recv/ch2/pos[2]} {BRAM_SPI_i/receiver_0/inst/recv/ch2/pos[3]}]]
set_property src_info {type:XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 28 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {BRAM_SPI_i/receiver_0/inst/recv/ch2/din_d[0]} {BRAM_SPI_i/receiver_0/inst/recv/ch2/din_d[1]} {BRAM_SPI_i/receiver_0/inst/recv/ch2/din_d[2]} {BRAM_SPI_i/receiver_0/inst/recv/ch2/din_d[3]} {BRAM_SPI_i/receiver_0/inst/recv/ch2/din_d[4]} {BRAM_SPI_i/receiver_0/inst/recv/ch2/din_d[5]} {BRAM_SPI_i/receiver_0/inst/recv/ch2/din_d[6]} {BRAM_SPI_i/receiver_0/inst/recv/ch2/din_d[7]} {BRAM_SPI_i/receiver_0/inst/recv/ch2/din_d[8]} {BRAM_SPI_i/receiver_0/inst/recv/ch2/din_d[9]} {BRAM_SPI_i/receiver_0/inst/recv/ch2/din_d[10]} {BRAM_SPI_i/receiver_0/inst/recv/ch2/din_d[11]} {BRAM_SPI_i/receiver_0/inst/recv/ch2/din_d[12]} {BRAM_SPI_i/receiver_0/inst/recv/ch2/din_d[13]} {BRAM_SPI_i/receiver_0/inst/recv/ch2/din_d[14]} {BRAM_SPI_i/receiver_0/inst/recv/ch2/din_d[15]} {BRAM_SPI_i/receiver_0/inst/recv/ch2/din_d[16]} {BRAM_SPI_i/receiver_0/inst/recv/ch2/din_d[17]} {BRAM_SPI_i/receiver_0/inst/recv/ch2/din_d[18]} {BRAM_SPI_i/receiver_0/inst/recv/ch2/din_d[19]} {BRAM_SPI_i/receiver_0/inst/recv/ch2/din_d[20]} {BRAM_SPI_i/receiver_0/inst/recv/ch2/din_d[21]} {BRAM_SPI_i/receiver_0/inst/recv/ch2/din_d[22]} {BRAM_SPI_i/receiver_0/inst/recv/ch2/din_d[23]} {BRAM_SPI_i/receiver_0/inst/recv/ch2/din_d[24]} {BRAM_SPI_i/receiver_0/inst/recv/ch2/din_d[25]} {BRAM_SPI_i/receiver_0/inst/recv/ch2/din_d[26]} {BRAM_SPI_i/receiver_0/inst/recv/ch2/din_d[27]}]]
set_property src_info {type:XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 12 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:188 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {BRAM_SPI_i/receiver_0/inst/recv/dout0[0]} {BRAM_SPI_i/receiver_0/inst/recv/dout0[1]} {BRAM_SPI_i/receiver_0/inst/recv/dout0[2]} {BRAM_SPI_i/receiver_0/inst/recv/dout0[3]} {BRAM_SPI_i/receiver_0/inst/recv/dout0[4]} {BRAM_SPI_i/receiver_0/inst/recv/dout0[5]} {BRAM_SPI_i/receiver_0/inst/recv/dout0[6]} {BRAM_SPI_i/receiver_0/inst/recv/dout0[7]} {BRAM_SPI_i/receiver_0/inst/recv/dout0[8]} {BRAM_SPI_i/receiver_0/inst/recv/dout0[9]} {BRAM_SPI_i/receiver_0/inst/recv/dout0[10]} {BRAM_SPI_i/receiver_0/inst/recv/dout0[11]}]]
set_property src_info {type:XDC file:1 line:189 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 12 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:192 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {BRAM_SPI_i/receiver_0/inst/recv/dout1[0]} {BRAM_SPI_i/receiver_0/inst/recv/dout1[1]} {BRAM_SPI_i/receiver_0/inst/recv/dout1[2]} {BRAM_SPI_i/receiver_0/inst/recv/dout1[3]} {BRAM_SPI_i/receiver_0/inst/recv/dout1[4]} {BRAM_SPI_i/receiver_0/inst/recv/dout1[5]} {BRAM_SPI_i/receiver_0/inst/recv/dout1[6]} {BRAM_SPI_i/receiver_0/inst/recv/dout1[7]} {BRAM_SPI_i/receiver_0/inst/recv/dout1[8]} {BRAM_SPI_i/receiver_0/inst/recv/dout1[9]} {BRAM_SPI_i/receiver_0/inst/recv/dout1[10]} {BRAM_SPI_i/receiver_0/inst/recv/dout1[11]}]]
set_property src_info {type:XDC file:1 line:193 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 12 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:196 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {BRAM_SPI_i/receiver_0/inst/recv/dout2[0]} {BRAM_SPI_i/receiver_0/inst/recv/dout2[1]} {BRAM_SPI_i/receiver_0/inst/recv/dout2[2]} {BRAM_SPI_i/receiver_0/inst/recv/dout2[3]} {BRAM_SPI_i/receiver_0/inst/recv/dout2[4]} {BRAM_SPI_i/receiver_0/inst/recv/dout2[5]} {BRAM_SPI_i/receiver_0/inst/recv/dout2[6]} {BRAM_SPI_i/receiver_0/inst/recv/dout2[7]} {BRAM_SPI_i/receiver_0/inst/recv/dout2[8]} {BRAM_SPI_i/receiver_0/inst/recv/dout2[9]} {BRAM_SPI_i/receiver_0/inst/recv/dout2[10]} {BRAM_SPI_i/receiver_0/inst/recv/dout2[11]}]]
set_property src_info {type:XDC file:1 line:197 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 12 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:200 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {BRAM_SPI_i/receiver_0/inst/recv/dout3[0]} {BRAM_SPI_i/receiver_0/inst/recv/dout3[1]} {BRAM_SPI_i/receiver_0/inst/recv/dout3[2]} {BRAM_SPI_i/receiver_0/inst/recv/dout3[3]} {BRAM_SPI_i/receiver_0/inst/recv/dout3[4]} {BRAM_SPI_i/receiver_0/inst/recv/dout3[5]} {BRAM_SPI_i/receiver_0/inst/recv/dout3[6]} {BRAM_SPI_i/receiver_0/inst/recv/dout3[7]} {BRAM_SPI_i/receiver_0/inst/recv/dout3[8]} {BRAM_SPI_i/receiver_0/inst/recv/dout3[9]} {BRAM_SPI_i/receiver_0/inst/recv/dout3[10]} {BRAM_SPI_i/receiver_0/inst/recv/dout3[11]}]]
set_property src_info {type:XDC file:1 line:201 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:204 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[0]} {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[1]} {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[2]} {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[3]} {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[4]} {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[5]} {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[6]} {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[7]} {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[8]} {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[9]} {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[10]} {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[11]} {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[12]} {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[13]} {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[14]} {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[15]} {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[16]} {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[17]} {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[18]} {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[19]} {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[20]} {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[21]} {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[22]} {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[23]} {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[24]} {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[25]} {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[26]} {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[27]} {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[28]} {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[29]} {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[30]} {BRAM_SPI_i/receiver_0/inst/ser2par/data_in_to_device[31]}]]
set_property src_info {type:XDC file:1 line:205 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 28 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:208 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {BRAM_SPI_i/receiver_0/inst/recv/ch3/din_d[0]} {BRAM_SPI_i/receiver_0/inst/recv/ch3/din_d[1]} {BRAM_SPI_i/receiver_0/inst/recv/ch3/din_d[2]} {BRAM_SPI_i/receiver_0/inst/recv/ch3/din_d[3]} {BRAM_SPI_i/receiver_0/inst/recv/ch3/din_d[4]} {BRAM_SPI_i/receiver_0/inst/recv/ch3/din_d[5]} {BRAM_SPI_i/receiver_0/inst/recv/ch3/din_d[6]} {BRAM_SPI_i/receiver_0/inst/recv/ch3/din_d[7]} {BRAM_SPI_i/receiver_0/inst/recv/ch3/din_d[8]} {BRAM_SPI_i/receiver_0/inst/recv/ch3/din_d[9]} {BRAM_SPI_i/receiver_0/inst/recv/ch3/din_d[10]} {BRAM_SPI_i/receiver_0/inst/recv/ch3/din_d[11]} {BRAM_SPI_i/receiver_0/inst/recv/ch3/din_d[12]} {BRAM_SPI_i/receiver_0/inst/recv/ch3/din_d[13]} {BRAM_SPI_i/receiver_0/inst/recv/ch3/din_d[14]} {BRAM_SPI_i/receiver_0/inst/recv/ch3/din_d[15]} {BRAM_SPI_i/receiver_0/inst/recv/ch3/din_d[16]} {BRAM_SPI_i/receiver_0/inst/recv/ch3/din_d[17]} {BRAM_SPI_i/receiver_0/inst/recv/ch3/din_d[18]} {BRAM_SPI_i/receiver_0/inst/recv/ch3/din_d[19]} {BRAM_SPI_i/receiver_0/inst/recv/ch3/din_d[20]} {BRAM_SPI_i/receiver_0/inst/recv/ch3/din_d[21]} {BRAM_SPI_i/receiver_0/inst/recv/ch3/din_d[22]} {BRAM_SPI_i/receiver_0/inst/recv/ch3/din_d[23]} {BRAM_SPI_i/receiver_0/inst/recv/ch3/din_d[24]} {BRAM_SPI_i/receiver_0/inst/recv/ch3/din_d[25]} {BRAM_SPI_i/receiver_0/inst/recv/ch3/din_d[26]} {BRAM_SPI_i/receiver_0/inst/recv/ch3/din_d[27]}]]
set_property src_info {type:XDC file:1 line:209 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:212 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list {BRAM_SPI_i/receiver_0/inst/recv/ch3/pos[0]} {BRAM_SPI_i/receiver_0/inst/recv/ch3/pos[1]} {BRAM_SPI_i/receiver_0/inst/recv/ch3/pos[2]} {BRAM_SPI_i/receiver_0/inst/recv/ch3/pos[3]}]]
set_property src_info {type:XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 28 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:216 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list {BRAM_SPI_i/receiver_0/inst/recv/ch0/din_d[0]} {BRAM_SPI_i/receiver_0/inst/recv/ch0/din_d[1]} {BRAM_SPI_i/receiver_0/inst/recv/ch0/din_d[2]} {BRAM_SPI_i/receiver_0/inst/recv/ch0/din_d[3]} {BRAM_SPI_i/receiver_0/inst/recv/ch0/din_d[4]} {BRAM_SPI_i/receiver_0/inst/recv/ch0/din_d[5]} {BRAM_SPI_i/receiver_0/inst/recv/ch0/din_d[6]} {BRAM_SPI_i/receiver_0/inst/recv/ch0/din_d[7]} {BRAM_SPI_i/receiver_0/inst/recv/ch0/din_d[8]} {BRAM_SPI_i/receiver_0/inst/recv/ch0/din_d[9]} {BRAM_SPI_i/receiver_0/inst/recv/ch0/din_d[10]} {BRAM_SPI_i/receiver_0/inst/recv/ch0/din_d[11]} {BRAM_SPI_i/receiver_0/inst/recv/ch0/din_d[12]} {BRAM_SPI_i/receiver_0/inst/recv/ch0/din_d[13]} {BRAM_SPI_i/receiver_0/inst/recv/ch0/din_d[14]} {BRAM_SPI_i/receiver_0/inst/recv/ch0/din_d[15]} {BRAM_SPI_i/receiver_0/inst/recv/ch0/din_d[16]} {BRAM_SPI_i/receiver_0/inst/recv/ch0/din_d[17]} {BRAM_SPI_i/receiver_0/inst/recv/ch0/din_d[18]} {BRAM_SPI_i/receiver_0/inst/recv/ch0/din_d[19]} {BRAM_SPI_i/receiver_0/inst/recv/ch0/din_d[20]} {BRAM_SPI_i/receiver_0/inst/recv/ch0/din_d[21]} {BRAM_SPI_i/receiver_0/inst/recv/ch0/din_d[22]} {BRAM_SPI_i/receiver_0/inst/recv/ch0/din_d[23]} {BRAM_SPI_i/receiver_0/inst/recv/ch0/din_d[24]} {BRAM_SPI_i/receiver_0/inst/recv/ch0/din_d[25]} {BRAM_SPI_i/receiver_0/inst/recv/ch0/din_d[26]} {BRAM_SPI_i/receiver_0/inst/recv/ch0/din_d[27]}]]
set_property src_info {type:XDC file:1 line:217 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:220 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list {BRAM_SPI_i/receiver_0/inst/recv/ch0/pos[0]} {BRAM_SPI_i/receiver_0/inst/recv/ch0/pos[1]} {BRAM_SPI_i/receiver_0/inst/recv/ch0/pos[2]} {BRAM_SPI_i/receiver_0/inst/recv/ch0/pos[3]}]]
set_property src_info {type:XDC file:1 line:221 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:224 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list {BRAM_SPI_i/receiver_0/inst/recv/ch1/pos[0]} {BRAM_SPI_i/receiver_0/inst/recv/ch1/pos[1]} {BRAM_SPI_i/receiver_0/inst/recv/ch1/pos[2]} {BRAM_SPI_i/receiver_0/inst/recv/ch1/pos[3]}]]
set_property src_info {type:XDC file:1 line:225 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 28 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:228 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list {BRAM_SPI_i/receiver_0/inst/recv/ch1/din_d[0]} {BRAM_SPI_i/receiver_0/inst/recv/ch1/din_d[1]} {BRAM_SPI_i/receiver_0/inst/recv/ch1/din_d[2]} {BRAM_SPI_i/receiver_0/inst/recv/ch1/din_d[3]} {BRAM_SPI_i/receiver_0/inst/recv/ch1/din_d[4]} {BRAM_SPI_i/receiver_0/inst/recv/ch1/din_d[5]} {BRAM_SPI_i/receiver_0/inst/recv/ch1/din_d[6]} {BRAM_SPI_i/receiver_0/inst/recv/ch1/din_d[7]} {BRAM_SPI_i/receiver_0/inst/recv/ch1/din_d[8]} {BRAM_SPI_i/receiver_0/inst/recv/ch1/din_d[9]} {BRAM_SPI_i/receiver_0/inst/recv/ch1/din_d[10]} {BRAM_SPI_i/receiver_0/inst/recv/ch1/din_d[11]} {BRAM_SPI_i/receiver_0/inst/recv/ch1/din_d[12]} {BRAM_SPI_i/receiver_0/inst/recv/ch1/din_d[13]} {BRAM_SPI_i/receiver_0/inst/recv/ch1/din_d[14]} {BRAM_SPI_i/receiver_0/inst/recv/ch1/din_d[15]} {BRAM_SPI_i/receiver_0/inst/recv/ch1/din_d[16]} {BRAM_SPI_i/receiver_0/inst/recv/ch1/din_d[17]} {BRAM_SPI_i/receiver_0/inst/recv/ch1/din_d[18]} {BRAM_SPI_i/receiver_0/inst/recv/ch1/din_d[19]} {BRAM_SPI_i/receiver_0/inst/recv/ch1/din_d[20]} {BRAM_SPI_i/receiver_0/inst/recv/ch1/din_d[21]} {BRAM_SPI_i/receiver_0/inst/recv/ch1/din_d[22]} {BRAM_SPI_i/receiver_0/inst/recv/ch1/din_d[23]} {BRAM_SPI_i/receiver_0/inst/recv/ch1/din_d[24]} {BRAM_SPI_i/receiver_0/inst/recv/ch1/din_d[25]} {BRAM_SPI_i/receiver_0/inst/recv/ch1/din_d[26]} {BRAM_SPI_i/receiver_0/inst/recv/ch1/din_d[27]}]]
set_property src_info {type:XDC file:1 line:229 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:232 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list BRAM_SPI_i/receiver_0/inst/ser2par/inst/data_in_from_pins_int_0]]
set_property src_info {type:XDC file:1 line:233 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:235 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:236 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list BRAM_SPI_i/receiver_0/inst/ser2par/inst/data_in_from_pins_int_1]]
set_property src_info {type:XDC file:1 line:237 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:1 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:1 line:240 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe15 [get_nets [list BRAM_SPI_i/receiver_0/inst/ser2par/inst/data_in_from_pins_int_2]]
set_property src_info {type:XDC file:1 line:241 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:1 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:1 line:244 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe16 [get_nets [list BRAM_SPI_i/receiver_0/inst/ser2par/inst/data_in_from_pins_int_3]]
set_property src_info {type:XDC file:1 line:245 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:1 line:247 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:1 line:248 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe17 [get_nets [list BRAM_SPI_i/receiver_0/inst/recv/wr0]]
set_property src_info {type:XDC file:1 line:249 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:1 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:1 line:252 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe18 [get_nets [list BRAM_SPI_i/receiver_0/inst/recv/wr1]]
set_property src_info {type:XDC file:1 line:253 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:1 line:255 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:1 line:256 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe19 [get_nets [list BRAM_SPI_i/receiver_0/inst/recv/wr2]]
set_property src_info {type:XDC file:1 line:257 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:1 line:259 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:1 line:260 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe20 [get_nets [list BRAM_SPI_i/receiver_0/inst/recv/wr3]]
set_property src_info {type:XDC file:1 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:264 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk_out]
