# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/xilinx_2017/Projects/gsense2020_v121/gsense2020_v121.srcs/sources_1/bd/BRAM_SPI/ip/BRAM_SPI_StoreImg_0_1/BRAM_SPI_StoreImg_0_1.xci
# IP: The module: 'BRAM_SPI_StoreImg_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/xilinx_2017/Projects/gsense2020_v121/gsense2020_v121.srcs/sources_1/bd/BRAM_SPI/ip/BRAM_SPI_StoreImg_0_1/src/fifo_generator_for_store_1/fifo_generator_for_store.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_generator_for_store || ORIG_REF_NAME==fifo_generator_for_store} -quiet] -quiet

# XDC: d:/xilinx_2017/Projects/gsense2020_v121/gsense2020_v121.srcs/sources_1/bd/BRAM_SPI/ip/BRAM_SPI_StoreImg_0_1/src/fifo_generator_for_store_1/fifo_generator_for_store.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_for_store || ORIG_REF_NAME==fifo_generator_for_store} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: D:/xilinx_2017/Projects/gsense2020_v121/gsense2020_v121.srcs/sources_1/bd/BRAM_SPI/ip/BRAM_SPI_StoreImg_0_1/BRAM_SPI_StoreImg_0_1.xci
# IP: The module: 'BRAM_SPI_StoreImg_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/xilinx_2017/Projects/gsense2020_v121/gsense2020_v121.srcs/sources_1/bd/BRAM_SPI/ip/BRAM_SPI_StoreImg_0_1/src/fifo_generator_for_store_1/fifo_generator_for_store.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_generator_for_store || ORIG_REF_NAME==fifo_generator_for_store} -quiet] -quiet

# XDC: d:/xilinx_2017/Projects/gsense2020_v121/gsense2020_v121.srcs/sources_1/bd/BRAM_SPI/ip/BRAM_SPI_StoreImg_0_1/src/fifo_generator_for_store_1/fifo_generator_for_store.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_for_store || ORIG_REF_NAME==fifo_generator_for_store} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
