# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/spi_pin.xdc

# Block Designs: bd/BRAM_SPI/BRAM_SPI.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_SPI || ORIG_REF_NAME==BRAM_SPI} -quiet] -quiet

# IP: bd/BRAM_SPI/ip/BRAM_SPI_processing_system7_0_0/BRAM_SPI_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_SPI_processing_system7_0_0 || ORIG_REF_NAME==BRAM_SPI_processing_system7_0_0} -quiet] -quiet

# IP: bd/BRAM_SPI/ip/BRAM_SPI_axi_bram_ctrl_0_0/BRAM_SPI_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_SPI_axi_bram_ctrl_0_0 || ORIG_REF_NAME==BRAM_SPI_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/BRAM_SPI/ip/BRAM_SPI_blk_mem_gen_0_0/BRAM_SPI_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_SPI_blk_mem_gen_0_0 || ORIG_REF_NAME==BRAM_SPI_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/BRAM_SPI/ip/BRAM_SPI_spi_config_0_0/BRAM_SPI_spi_config_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_SPI_spi_config_0_0 || ORIG_REF_NAME==BRAM_SPI_spi_config_0_0} -quiet] -quiet

# IP: bd/BRAM_SPI/ip/BRAM_SPI_clk_wiz_0_0/BRAM_SPI_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_SPI_clk_wiz_0_0 || ORIG_REF_NAME==BRAM_SPI_clk_wiz_0_0} -quiet] -quiet

# IP: bd/BRAM_SPI/ip/BRAM_SPI_axi_interconnect_0_0/BRAM_SPI_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_SPI_axi_interconnect_0_0 || ORIG_REF_NAME==BRAM_SPI_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/BRAM_SPI/ip/BRAM_SPI_xbar_0/BRAM_SPI_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_SPI_xbar_0 || ORIG_REF_NAME==BRAM_SPI_xbar_0} -quiet] -quiet

# IP: bd/BRAM_SPI/ip/BRAM_SPI_decoder_0_0/BRAM_SPI_decoder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_SPI_decoder_0_0 || ORIG_REF_NAME==BRAM_SPI_decoder_0_0} -quiet] -quiet

# IP: bd/BRAM_SPI/ip/BRAM_SPI_proc_sys_reset_recv_0/BRAM_SPI_proc_sys_reset_recv_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_SPI_proc_sys_reset_recv_0 || ORIG_REF_NAME==BRAM_SPI_proc_sys_reset_recv_0} -quiet] -quiet

# IP: bd/BRAM_SPI/ip/BRAM_SPI_receiver_0_0/BRAM_SPI_receiver_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_SPI_receiver_0_0 || ORIG_REF_NAME==BRAM_SPI_receiver_0_0} -quiet] -quiet

# IP: bd/BRAM_SPI/ip/BRAM_SPI_proc_sys_reset_0_0/BRAM_SPI_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_SPI_proc_sys_reset_0_0 || ORIG_REF_NAME==BRAM_SPI_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/BRAM_SPI/ip/BRAM_SPI_axi_interconnect_1_0/BRAM_SPI_axi_interconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_SPI_axi_interconnect_1_0 || ORIG_REF_NAME==BRAM_SPI_axi_interconnect_1_0} -quiet] -quiet

# IP: bd/BRAM_SPI/ip/BRAM_SPI_StoreImg_0_0/BRAM_SPI_StoreImg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_SPI_StoreImg_0_0 || ORIG_REF_NAME==BRAM_SPI_StoreImg_0_0} -quiet] -quiet

# IP: bd/BRAM_SPI/ip/BRAM_SPI_s00_regslice_0/BRAM_SPI_s00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_SPI_s00_regslice_0 || ORIG_REF_NAME==BRAM_SPI_s00_regslice_0} -quiet] -quiet

# IP: bd/BRAM_SPI/ip/BRAM_SPI_auto_pc_1/BRAM_SPI_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_SPI_auto_pc_1 || ORIG_REF_NAME==BRAM_SPI_auto_pc_1} -quiet] -quiet

# IP: bd/BRAM_SPI/ip/BRAM_SPI_auto_us_df_0/BRAM_SPI_auto_us_df_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_SPI_auto_us_df_0 || ORIG_REF_NAME==BRAM_SPI_auto_us_df_0} -quiet] -quiet

# IP: bd/BRAM_SPI/ip/BRAM_SPI_auto_pc_0/BRAM_SPI_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_SPI_auto_pc_0 || ORIG_REF_NAME==BRAM_SPI_auto_pc_0} -quiet] -quiet

# XDC: bd/BRAM_SPI/BRAM_SPI_ooc.xdc
